### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by DeerSong** [mengcz13/fusedive#3]
```
2017-05-28 20:43:08.357 MainThread: [dropbox] Request to files/list_folder
2017-05-28 20:43:08.376 MainThread: [requests.packages.urllib3.connectionpool] Connection pool is full, discarding connection: api.dropboxapi.com
Traceback (most recent call last):
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/util/timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fusedive_mem.py", line 193, in <module>
    main()
  File "fusedive_mem.py", line 171, in main
    operations = DropboxOperations(dbx, options.tmpdir)
  File "fusedive_mem.py", line 53, in __init__
    self._init_dropbox()
  File "fusedive_mem.py", line 56, in _init_dropbox
    y = self.dbx.files_list_folder('', recursive=True)
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/dropbox/base.py", line 715, in files_list_folder
    None,
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/dropbox/dropbox.py", line 239, in request
    timeout=timeout)
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/dropbox/dropbox.py", line 330, in request_json_string_with_retry
    timeout=timeout)
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/dropbox/dropbox.py", line 414, in request_json_string
    timeout=timeout,
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/sessions.py", line 570, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/sessions.py", line 523, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/connectionpool.py", line 587, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/connectionpool.py", line 302, in _get_timeout
    return Timeout.from_float(timeout)
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/home/deersong/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.
```

**Comment by mengcz13** [comment]
```
ss-local -s "45.76.172.133" -p "10900" -l "1080" -k "fusedive2017" -m "aes-256-gcm" -uv
```
